# Generated by Django 2.2.4 on 2019-09-12 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubros', '0001_initial'),
        ('productos', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='rubro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productosXrubro', to='rubros.Rubros'),
            preserve_default=False,
        ),
    ]
